apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC10pGt13ihT3ssQAO/h/oMSSi6++0f3S45NNUlLQhqPqCxLH96CfvBWd4JKSAx0uEPoGERwLZB53fcNbjtTHsAZwsZzl8r1BSAjOy/jRvUlq5hxE1CVqxCaQgf8sMmeVZd+yAomFPmtIqbOR/D1pomNpxY8+GVybl4NA61OxtgvpEMxdkdi5qReHtawdUNtkOxyYpnbd1CaEKcthW5ks/pxo3ZzhILmEWhfsPGJhJofqT1uvvOQrTg6fKPGn9f4Yoc6+BrY7X1eIiahHwUf4LINsWR6rO/KGYsIlqodUgAJXMj117MJBTezpIM7lqZBxqP3RaEjEPYNzh7fp88/yQOTL747d0P6yDF/5v9xzCkZIzV2F0ehQlnmMnfbib/zZahVNhDL2I7TK/oAOhEZVUh4Nb1n9uenIPXJgBUVNyyX3QMJlD0Hapf0nnKefAaYqSH5CbI+t0LfmnbL9ssthBnMaXG57y29oULaqJAIzwDPUpDeBuO00DHqR8AplxXC//t1TfZXm2R0t4/I5e4J7UJPawwKIl2sSa2ncBMZ1u/ZAUCqlcAuWps04Q27bhr090jHNRB5hrwUoD12dHC35n4BqDrJICWF6GFiH0/uq3nUWlmj7S6Pt2L1xMxDOH+ip7OLMWGnq1iupl2ahfRqMQ0FeoOlFT1z9q5npnTGHnn2mGM4pXp5Hg8JxgoPbGxzTzgUhey16SLWOXhIZl2gr+TtKGfCSTYKkAdu19237wkJ7AQ/pdU4LYJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

